# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-deploy
  template:
    metadata:
      labels:
        app: springboot-deploy
    spec:
      containers:
        - name: springboot-deploy
          image: vanderloureiro/springboot-deploy:latest
          ports:
            - containerPort: 8080
          env:
            - name: PARAMETRO_EXEMPLO
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: parametro-exemplo
---
# service
apiVersion: v1
kind: Service
metadata:
  name: springboot-deploy-service
spec:
  type: NodePort
  selector:
    app: springboot-deploy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30123
